"""Shared setup used by every example script.

Loads the random dataset generated by ``gen_data.py`` and picks the
appropriate device. Examples import ``load`` and ``device`` from here so
each script focuses on one distinct feature.
"""
import os
import numpy as np
import torch


def _data_dir() -> str:
    return os.path.join(os.path.dirname(__file__), "data")


def paths() -> dict:
    """Return absolute paths to the example .npy files.

    Distributed/partitioned mode requires *file paths* (not arrays), so
    examples that run under torchrun pass these strings directly to
    ``BaseData`` / ``*SubSampler``.
    """
    d = _data_dir()
    names = ["X", "y", "w", "config_idxs", "enrow_mask"]
    return {n: os.path.join(d, f"{n}.npy") for n in names}


def load() -> dict:
    """Load the dataset into memory as numpy arrays."""
    return {k: np.load(v) for k, v in paths().items()}


def device() -> str:
    """Single-device helper: ``'cuda:0'`` if a GPU is visible, else ``'cpu'``."""
    return "cuda:0" if torch.cuda.is_available() else "cpu"
